### ISSUE TITLE
Add plpythonu extension on Postgre database

### ISSUE THREAD

**Issue by florianwns** [metwork-framework/mfbase#107]
I want to use the `plpythonu` extension with my mfbase/postgre plugin, but it's not possible to install extensions.

See [here](https://www.postgresql.org/docs/9.1/plpython.html)

Is it possible to add this extension like an mfbase module option ?

Thx a lot ! 

Gitter : [https://gitter.im/metwork-framework/community-fr?at=5e5fb62c376d882250ce9eff]()

**Comment by thefab** [comment]
as it's unsafe extension, we need a module level config.ini flag (false by default) to activate or not the extension during mfbase.init

**Comment by thebaptiste** [comment]
For internal Metwork reasons, it could be difficult to add python extensions in postgresql build.

**Comment by thebaptiste** [comment]
Not so difficult finally. The extension has been added in mfext. We have to allow its usage in mfbase (not by default).

**Comment by thebaptiste** [comment]
The added extension is `plpython3u` (python 3 version of `plpythonu`). You will need to use it under this name, for example : 
```
CREATE FUNCTION funcname (argument-list)
  RETURNS return-type
AS $$
  # PL/Python function body
$$ LANGUAGE plpython3u;
```
If you want this extension to be created in your mfbase installation, you need to set `plpython3u=1`  in the postgresql section of mfbase config.ini file (by default it is set to 0).
If you do so, the extension will be created for the metwork database and for your plugins databases.

**Comment by thebaptiste** [comment]
Done
