### ISSUE TITLE
impossible to install a mfbase plugin under mageia 7

### ISSUE THREAD

**Issue by ghost** [metwork-framework/mfbase#119]
Following the quickstart guide:
https://metwork-framework.github.io/quickstart/5_database.html

when we try to install a database plugin:
```console
$ plugins.install foo-0.0.1-1.metwork.mfbase.plugin
```
we obtain an error message:
```console
ERROR: the module is not initialized
```
whether mfbase was started with:
```console
$ service metwork start
# or
$ mfbase.start  # as mfbase
```
Operating system:
```console
$ uname -r 
5.1.5-desktop-1.mga7
```
Note : the OS runs in a VirtualBox virtual machine

**Comment by thebaptiste** [comment]
If you run `mfbase.status` before installing your plugin, is everything ok ?

**Comment by thebaptiste** [comment]
Which version of Metwork do you use ?

**Comment by thebaptiste** [comment]
I made a few test in a mageia 7 docker container.
The system seems to consider that our crontab files are not valid (it's not specific to mfbase, same thing on mfserv).
`Traceback (most recent call last):
  File "/opt/metwork-mfext-0.9/opt/python3/bin/deploycron_file", line 11, in <module>
    sys.exit(main())
  File "/opt/metwork-mfext-0.9/opt/python3/lib/python3.7/site-packages/deploycron/cli_deploycron_file.py", line 20, in main
    deploycron.deploycron(filename=filepath)
  File "/opt/metwork-mfext-0.9/opt/python3/lib/python3.7/site-packages/deploycron/__init__.py", line 42, in deploycron
    _install_content(installed_content)
  File "/opt/metwork-mfext-0.9/opt/python3/lib/python3.7/site-packages/deploycron/__init__.py", line 119, in _install_content
    raise ValueError("failed to install crontab, check if crontab is "
ValueError: failed to install crontab, check if crontab is valid
`

**Comment by thebaptiste** [comment]
We do not support mageia anymore
