### ISSUE TITLE
postinstall script not launched during _plugins.postinstall

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfbase#207]
If I'm right (**postinstall** script not launched for mfbase plugin, not 100% sure),
either we add this functionality*
either we remove its reference from the doc:
https://github.com/metwork-framework/mfbase/blob/master/docs/_plugin_ref_interesting_files.md

*by adding:
```
if test -x "${PLUGIN_HOME}/postinstall"; then
    echo "Running post-installation plugin tasks"
    plugin_wrapper --cwd "${PLUGIN_HOME}" "${PLUGIN_HOME}/postinstall"
fi
```
in https://github.com/metwork-framework/mfbase/blob/master/adm/_plugins.postinstall

**Comment by thebaptiste** [comment]
For mfserv and mfdata `_plugins.postinstall` scripts, this seems to be done by the line : 

`"${MFEXT_HOME}/bin/_plugins.postinstall" "${1}" "${2}" "${3}"`

**Comment by matthieumarrast** [comment]
Yes, it should works!
For your information in my mfbase plugin postinstall script I add this below, it allows creating the django test database (used for UT and integration tests):
```
#!/bin/bash
# add postgresql authorizations, for django purpose
echo "host    all plugin_<foo>    0.0.0.0/0   md5" >> ~/var/pgsql/pg_hba.conf
echo "host    all plugin_<foo>    ::1/128   md5" >> ~/var/pgsql/pg_hba.conf
echo "Authorizations added. You must restart mfbase."
exit 0
```
