### ISSUE TITLE
mktemp issue while executing plugin_env

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfbase#212]
Command `plugin_env` for a mfbase plugin raise error:
```
mktemp: impossible de créer le fichier à partir du modèle « /home/mfbase/tmp/<plugin>/tmp.XXXXXXXXXX »: Aucun fichier ou dossier de ce type
bash: : Aucun fichier ou dossier de ce type
cat: '': Aucun fichier ou dossier de ce type
```

=> reason:  the directory "/home/mfbase/tmp/\<plugin>" (path provided by $TMPDIR variable) does not exist. 
`mktemp` command is executed in commands layer_load/unload in `/opt/metwork-mfext-2.1/lib/bash_utils.sh`

=> context: after a migration from mfbase 2.0 to mfbase 2.1

**Comment by thebaptiste** [comment]
The problem occurs if the directory has been removed for some reason (`mfbase.init` for instance) but the env variable is set in `.configuration_cache` (because of a previous `plugin_env`)

**Comment by thebaptiste** [comment]
Done
