### ISSUE TITLE
mfbase plugins.uninstall doesn't drop the database if a user is connected

### ISSUE THREAD

**Issue by dearith** [metwork-framework/mfbase#23]
Uninstalling a mfbase plugin doesn't always drop the database.

It seems  if a user is connected to the database, the plugin is not able to drop the database : 
output returned by the plugins.uninstall command is :

mfbase@localhost ~]$ plugins.uninstall foo
- Uninstalling plugin foo...                               [ RUNNING ]error during postuninstall:
===== BASH COMMAND =======================
_plugins.postuninstall foo 0.0.1 1
===== BASH RETURN CODE ===================
1
                                                          [ OK ]

**Comment by thefab** [comment]
confirmed if a user is connected on the database during the plugins.uninstall

**Comment by thefab** [comment]
not easy:
see https://dba.stackexchange.com/questions/11893/force-drop-db-while-others-may-be-connected

**Comment by thefab** [comment]
some progress here : now the plugins.uninstall command does not work in this particular case and the plugin is not removed
