### ISSUE TITLE
Using docker volume mechanism for postgresql data (~/var/pgsql) can triggers a database deletion (due to mfbase.init)

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfbase#238]
It's a common usage to use a docker volume for storing database data and allow the **data persistance**.
So we use the image `metwork/mfbaseplugins-centos8-buildimage` to start a mfbase container into a **docker-compose cluster**.

Below is an example of a simplified docker-compose definition, with the mfbase container

docker-compose.yml
```
version: '3.8'

services:
  metbase:
    image : metwork/mfbaseplugins-centos8-buildimage:release_2.1
    # volume is mount as "root" so we must give mfbase:metwork rights
    command: bash -c 'chown -R mfbase:metwork /home/mfbase/var && su - mfbase -c "mfbase.start && tail -f ~/log/*"'
    volumes:
      - /volumes/pgsql:/home/mfbase/var/pgsql
```

## Problem
On first start, an `mfbase.init` command is triggered (for initializing the database) while starting the module.
An attempt to delete the folder `/home/mfbase/var/pgsql` is made :

```
docker-metbase-1  | *****************************************
docker-metbase-1  | *****     MFBASE INITIALIZATION     *****
docker-metbase-1  | *****************************************
docker-metbase-1  |   
docker-metbase-1  | - Stopping (if running) mfbase module...[ OK ]
docker-metbase-1  | - Cleaning /home/mfbase/tmp...[ OK ]
docker-metbase-1  | - Cleaning /home/mfbase/var...[ OK ]
docker-metbase-1  | - Cleaning /home/mfbase/log...[ OK ]
docker-metbase-1  | - Checking postgresql data dir...[ WARNING ] (already exist)
docker-metbase-1  | - Removing /home/mfbase/var/pgsql...[ ERROR ]
docker-metbase-1  | BIG PROBLEM => EXITING
```

Inside the container the path (/home/mfbase/var/pgsql) cannot be removed as it is a docker volume mount. It's a rather locical protection.
Below is the error message while trying to remove it:
```
# rm -rf pgsql/
rm: cannot remove 'pgsql/': Device or resource busy
```
(note the `Cleaning /home/mfbase/var...` [function `cleanup_directories()` of https://github.com/metwork-framework/mfext/blob/master/adm/bash_utils.sh] which can be dangerous)

So the team cannot "volumize" this pgsql folder, as it avoids the container to start.

## Workaround

"volumize" the upstream (i.e ~/var) folder :
```
    volumes:
      - /volumes/mfbase_var:/home/mfbase/var
````
=> also the ~/var/pgsql directory is not "protected" anymore. On first start, an `mfbase.init` will delete it... and all the data will be lost (but theoretically there is none).
_Moreover I think it's not a good solution as it writes in the volume some module runtime files which must not be volumized: nginx.socket, status, nginx.pid, circus.socket, uuid..._

Unfortunately, this `mfbase.init` is not only launched on first `mfbase.start` !! if you look at the script `mfxxx.start` (https://github.com/metwork-framework/mfext/blob/master/adm/templates/mfxxx.start), we can notice the init is launched on module startup as soon as `~/var/plugins` folder is missing. That's rather DANGEROUS in a docker-compose cluster context ! ->
```
NOINIT=0
if test "${1:-}" = "NOINIT"; then
    NOINIT=1
fi
...
if test "${NOINIT}" = "0"; then
    if ! test -d ${MFMODULE_RUNTIME_HOME}/var/plugins; then
        {{MFMODULE_LOWERCASE}}.init
    fi
```

So I open this issue because we have experienced the **LOSS of a database** while trying to set this volume from `/volumes/pgsql:/home/mfbase/var` (the above workaround, but with pretty bad source name) to `/volumes/pgsql:/home/mfbase/var/pgsql` (my mistake was to use the same volume path and to append "pgsql") mapping, because the "plugins" directory were not coming anymore with the volume so the start triggered the init which deleted the database data...

Note: we have noticed the **noinit** option exists (`mfbase.start NOINIT`) but during the FIRST start we must init...

## Solution

Possible solutions are : 
- if `~/var/pgsql` is a volume (i.e raise "Device or resource busy" inside container), do not delete it !
or
- do not trigger `mfbase.init` if `~/var/plugins/` does not exist, what's the purpose of that ?
...

**Comment by thebaptiste** [comment]
I'm not in favor of the first solution : I don't see any good reason why the first call to `mfbase.init` shouldn't delete the data base. It would no longer be an initialization...

But of course we must prevent `mfbase.init` to be triggered without any good reason. I don't understand why `mfbase.init` is triggered when `~/var/plugins` does not exist (especially since this directory seems to be recreated by any call to `mfbase.status`). We could try to remove this.

That said, I don't see any major problem with your workaround.

**Comment by thebaptiste** [comment]
I think this call to mfxxx.init inside mfxxx.start was linked to the next command for mfdata and mfserv : 
```
    {% if MFMODULE != "MFBASE" %}
    _install_or_update_configured_plugins.py
    {% endif %}
```
(installing plugins `switch` and `guess_file_type` for mfdata)

But the call to `_install_or_update_configured_plugins.py` create the missing directory `~/var/plugins`
So I don't see any reason to keep this call to `mfxxx.init` in `mfxxx.start`

**Comment by matthieumarrast** [comment]
Be careful, at very first start, the `init` must be done !
It is not said to the user to execute the init command but always the start command, cf. http://metwork-framework.org/pub/metwork/continuous_integration/docs/master/mfbase/020-quickstart/

**Comment by matthieumarrast** [comment]
I have pushed a commit by proposing to check the presence of `${MFMODULE_RUNTIME_HOME}/var/pgqsl` when mfbase, and `${MFMODULE_RUNTIME_HOME}/var/plugins` for other modules.
Also the database is not reinitialized (i.e deleted) when ~/var/plugins folder is missing, but only when the database is really missing.

**Comment by thebaptiste** [comment]
Closed by https://github.com/metwork-framework/mfext/pull/1563
