### ISSUE TITLE
.gitignore missing for new mfbase plugins

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfbase#257]
## Problem
I installed a new mfbase plugin and I noticed the file `.configuration_cache` is noticed in the git untracked file to be staged.

![image](https://github.com/metwork-framework/mfbase/assets/38913120/f8cbce6a-1224-473d-b778-7cc122e36df9)

It appears the default **.gitignore** file is missing.

## Analysis

The file **.gitignore** is located in folder https://github.com/metwork-framework/mfbase/tree/master/adm/templates/plugins/default instead of https://github.com/metwork-framework/mfbase/tree/master/adm/templates/plugins/default/%7B%7Bcookiecutter.name%7D%7D

## Solution
Move the file to the right folder.

**Comment by thebaptiste** [comment]
Closed by #258
