### ISSUE TITLE
max_connections in `postgresql.conf` should be configurable

### ISSUE THREAD

**Issue by thebaptiste** [metwork-framework/mfbase#275]
max_connections in `postgresql.conf` is set by default to 100.
Sometimes it's not enough. It should be configurable (keeping 100 as default)

(this was asked by Meteo-France users)

**Comment by thebaptiste** [comment]
Already done (master and release 2.2.5)

**Comment by matthieumarrast** [comment]
sorry but I updated to release 2.2.5 and the fix is not OK
you grep a line (starting with) `max_connections` whereas the line to fix starts with `#max_connections`.
the purpose of `^#\?` is to handle the cases where line is starting with # or not.
