### ISSUE TITLE
plugins.uninstall : add options or a message before uninstall

### ISSUE THREAD

**Issue by zevenements** [metwork-framework/mfbase#50]
Hi,

command 

> plugins.uninstall myplugin

 maybe needs options to keep data safe outside of the plugin before uninstall the plugin,
at least display an alert like " are you sure, because your database will be remove.." 

thx

**Comment by thefab** [comment]
we are not sure about what we want to do with this issue:

- maybe we can add this kind of "warning" but only in an "interactive session"
- we probably need a `plugins.dump/restore` command in `mfbase`
- [...]

Let's take some time to think about that

**Comment by thefab** [comment]
for the record:

- we have now `plugins.pgdump.sh` and `plugins.pgrestore.sh`
- the first one can be used to generate directly the `.sql` file played during plugin installation
