### ISSUE TITLE
Uppercase character in database name

### ISSUE THREAD

**Issue by matthieumarrast** [metwork-framework/mfbase#95]
Hello,

While creating a database with an uppercase character in the database name (ex: Foo), we face the below error while trying to connect to the database :
psql: FATAL:  password authentication failed for user "plugin_Foo"

Regards,
Matthieu

**Comment by thefab** [comment]
thanks @matthieumarrast for the bug report

**Comment by thefab** [comment]
https://medium.com/metwork-framework/mfbase-0-9-4-f3f801d68d9f
